### ISSUE TITLE
Rename this repository to ydata-profiling-service for consistency

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/ydata-profiling#1]
I would rename this repository to `ydata-profiling-service` as it is a service that provides [ydata-profiling](https://github.com/ydataai/ydata-profiling).

It allows to stay consistent with the other services' names as well.

After the renaming, the previous package `ydata-profiling` should be deleted from the [Packages](https://github.com/orgs/swiss-ai-center/packages) page in favor of the new package's name.

@Arnwald, would you be OK to take care of this?

**Comment by Arnwald** [comment]
Yes, I'm ok with that.
